"""Add business_category and description

Revision ID: 22cd2fd4b171
Revises: 54fe2ad7ef41
Create Date: 2026-05-08 11:29:11.273635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22cd2fd4b171'
down_revision: Union[str, None] = '54fe2ad7ef41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('business_category', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'description')
    op.drop_column('users', 'business_category')
    # ### end Alembic commands ###
